nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
