name: Build and publish library

on:
  push:
    branches: ['main']
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

permissions:
  actions: read
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn --immutable
      - run: yarn test
      - run: yarn build

      #      - name: Publish pino-logger
      #        if: github.ref == 'refs/heads/main'
      #        run: yarn npm publish
      #        working-directory: libs/pino-logger

      - name: Publish next-logger
        if: github.ref == 'refs/heads/main'
        run: yarn npm publish
        working-directory: libs/next-logger

  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://github-actions[bot]:$NAV_DS_TOKEN@github.com/$GITHUB_REPOSITORY.git
      - run: yarn version -i minor
      - run: yarn version -i minor
        working-directory: libs/next-logger
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version package.json)" && git push
